#!/usr/bin/env bash
# Generated from workflows/rabbitmq-blue-green-migration-30-stage-alternating.yaml

plan_stage "stage_01_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_02_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_03_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_04_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_05_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_06_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_07_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_08_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_09_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_10_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_11_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_12_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_13_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_14_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_15_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_16_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_17_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_18_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_19_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_20_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_21_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_22_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_23_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_24_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_25_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_26_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_27_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_28_b_to_a" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_29_a_to_b" "rabbitmq/blue_green_migration.sh"
plan_stage "stage_30_b_to_a" "rabbitmq/blue_green_migration.sh"
