apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-ef6f8f7452-order_b-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - order_b-1-default
  - order_b-2-default
  - order_b-3-default
  stages:
  - id: stage_01_mongodb_setup-rbac-drift-app
    service: mongodb
    case: setup-rbac-drift-app
    namespaces:
    - order_b-1-default
    namespace_binding:
      default: order_b-1-default
    max_attempts: 1
  - id: stage_02_cockroachdb_health-check-recovery
    service: cockroachdb
    case: health-check-recovery
    namespaces:
    - order_b-2-default
    namespace_binding:
      default: order_b-2-default
    max_attempts: 1
  - id: stage_03_rabbitmq-experiments_manual_monitoring
    service: rabbitmq-experiments
    case: manual_monitoring
    namespaces:
    - order_b-3-default
    namespace_binding:
      default: order_b-3-default
    max_attempts: 1
