apiVersion: v1
kind: Pod
metadata:
  name: openssl-toolbox
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: openssl-toolbox
spec:
  containers:
  - name: openssl
    image: alpine/openssl:3.1.4
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
  restartPolicy: Always
