apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-job-script
  labels:
    app.kubernetes.io/name: ray
    app.kubernetes.io/component: job-script
    bench.ray.cluster: ray
data:
  job.py: |
    import ray

    ray.init(address="ray://ray-head:10001")

    print("pong")

    ray.shutdown()
