apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-9780fc3b9d-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_mongodb_password-rotation
    service: mongodb
    case: password-rotation
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
