apiVersion: v1
kind: Service
metadata:
  name: mongodb-replica-svc
  namespace: mongodb
  labels:
    app: mongodb-replica
spec:
  clusterIP: None
  selector:
    app: mongodb-replica
  ports:
    - name: mongod
      port: 27017
      targetPort: 27017
