apiVersion: v1
kind: Secret
metadata:
  name: admin-user-password
type: Opaque
stringData:
  password: admin123password
---
apiVersion: v1
kind: Secret
metadata:
  name: app-user-password
type: Opaque
stringData:
  password: appuser123password
---
apiVersion: v1
kind: Secret
metadata:
  name: app-user-password-old
type: Opaque
stringData:
  password: appuser123password
---
apiVersion: v1
kind: Secret
metadata:
  name: app-user-password-next
type: Opaque
stringData:
  password: newAppUserPassword456
---
apiVersion: v1
kind: Secret
metadata:
  name: reporting-user-password
type: Opaque
stringData:
  password: reporting123password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
type: Opaque
stringData:
  keyfile: mongoKeyfile0123456789ABCDEF
