apiVersion: v1
kind: Pod
metadata:
  name: ray-client
  namespace: ray
  labels:
    app.kubernetes.io/name: ray
    app.kubernetes.io/component: client
    bench.ray.cluster: ray
spec:
  restartPolicy: Never
  containers:
    - name: ray-client
      image: rayproject/ray:2.9.0
      command: ["sh", "-c"]
      args:
        - |
          echo "ray client ready"
          sleep infinity
      volumeMounts:
        - name: job-script
          mountPath: /opt/job.py
          subPath: job.py
  volumes:
    - name: job-script
      configMap:
        name: ray-job-script
