apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-c3d9e8170e-history_mutated-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - history_mutated-1-source
  - history_mutated-1-target
  - history_mutated-2-default
  stages:
  - id: stage_01_demo_configmap-update-two-ns
    service: demo
    case: configmap-update-two-ns
    namespaces:
    - history_mutated-1-source
    - history_mutated-1-target
    namespace_binding:
      source: history_mutated-1-source
      target: history_mutated-1-target
    max_attempts: 1
  - id: stage_02_cockroachdb_decommission
    service: cockroachdb
    case: decommission
    namespaces:
    - history_mutated-2-default
    namespace_binding:
      default: history_mutated-2-default
    max_attempts: 1
