apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-c3d9e8170e-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_cockroachdb_decommission
    service: cockroachdb
    case: decommission
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
