apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-b3c77002a4-control-concat_stateful
spec:
  prompt_mode: concat_stateful
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_cockroachdb_cluster-settings
    service: cockroachdb
    case: cluster-settings
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
