apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-c0df6f7be0-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_mongodb_custom-roles
    service: mongodb
    case: custom-roles
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
