apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-e67ec90317-history_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - history_mutated-1-default
  - history_mutated-2-default
  stages:
  - id: stage_01_elasticsearch_seed-hosts-repair
    service: elasticsearch
    case: seed-hosts-repair
    namespaces:
    - history_mutated-1-default
    namespace_binding:
      default: history_mutated-1-default
    max_attempts: 1
  - id: stage_02_elasticsearch_file-realm-user-roles-merge
    service: elasticsearch
    case: file-realm-user-roles-merge
    namespaces:
    - history_mutated-2-default
    namespace_binding:
      default: history_mutated-2-default
    max_attempts: 1
