apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-886b972854-distractor_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - distractor_mutated-cluster_a
  stages:
  - id: stage_01_cockroachdb_deploy
    service: cockroachdb
    case: deploy
    namespaces:
    - distractor_mutated-cluster_a
    namespace_binding:
      default: distractor_mutated-cluster_a
    param_overrides:
      replica_count: 4
    max_attempts: 1
  - id: stage_02_cockroachdb_zone-config
    service: cockroachdb
    case: zone-config
    namespaces:
    - distractor_mutated-cluster_a
    namespace_binding:
      default: distractor_mutated-cluster_a
    param_overrides: {}
    max_attempts: 1
