apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  restartPolicy: Always
  containers:
    - name: curl
      image: curlimages/curl:8.6.0
      command:
        - /bin/sh
        - -c
        - sleep 3600
