apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-39ae063b17-order_b-concat_stateful
spec:
  prompt_mode: concat_stateful
  namespaces:
  - order_b-1-default
  - order_b-1-monitoring
  - order_b-2-default
  - order_b-3-default
  stages:
  - id: stage_01_mongodb_monitoring-integration
    service: mongodb
    case: monitoring-integration
    namespaces:
    - order_b-1-default
    - order_b-1-monitoring
    namespace_binding:
      default: order_b-1-default
      monitoring: order_b-1-monitoring
    max_attempts: 1
  - id: stage_02_spark_spark_sql_job_execution
    service: spark
    case: spark_sql_job_execution
    namespaces:
    - order_b-2-default
    namespace_binding:
      default: order_b-2-default
    max_attempts: 1
  - id: stage_03_spark_spark_worker_scaling
    service: spark
    case: spark_worker_scaling
    namespaces:
    - order_b-3-default
    namespace_binding:
      default: order_b-3-default
    max_attempts: 1
