apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crdb-cluster
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: crdb-cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
      app.kubernetes.io/instance: crdb-cluster
  endpoints:
    - port: http
      path: /_status/vars
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
