apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-5cf95e6c9b-order_b-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - order_b-1-default
  - order_b-2-default
  - order_b-3-default
  stages:
  - id: stage_01_rabbitmq-experiments_classic_queue
    service: rabbitmq-experiments
    case: classic_queue
    namespaces:
    - order_b-1-default
    namespace_binding:
      default: order_b-1-default
    max_attempts: 1
  - id: stage_02_elasticsearch_full-restart-upgrade-ha
    service: elasticsearch
    case: full-restart-upgrade-ha
    namespaces:
    - order_b-2-default
    namespace_binding:
      default: order_b-2-default
    max_attempts: 1
  - id: stage_03_rabbitmq-experiments_manual_tls_rotation
    service: rabbitmq-experiments
    case: manual_tls_rotation
    namespaces:
    - order_b-3-default
    namespace_binding:
      default: order_b-3-default
    max_attempts: 1
