apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-rs
  labels:
    app: mongo-rs
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo-rs
  template:
    metadata:
      labels:
        app: mongo-rs
    spec:
      containers:
        - name: mongod
          image: mongo:6.0
          command:
            - mongod
            - --replSet
            - rs0
            - --bind_ip_all
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}
