apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-3fb08cdba6-control-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - control-cluster_x
  stages:
  - id: stage_01_rabbitmq-experiments_manual_monitoring
    service: rabbitmq-experiments
    case: manual_monitoring
    namespaces:
    - control-cluster_x
    namespace_binding:
      default: control-cluster_x
    param_overrides: {}
    max_attempts: 1
