apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-edabcc4910-distractor_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - distractor_mutated-1-default
  - distractor_mutated-2-ingress
  - distractor_mutated-2-app
  stages:
  - id: stage_01_mongodb_health-check-recovery
    service: mongodb
    case: health-check-recovery
    namespaces:
    - distractor_mutated-1-default
    namespace_binding:
      default: distractor_mutated-1-default
    max_attempts: 1
  - id: stage_02_nginx-ingress_ingress_route_ready
    service: nginx-ingress
    case: ingress_route_ready
    namespaces:
    - distractor_mutated-2-ingress
    - distractor_mutated-2-app
    namespace_binding:
      ingress: distractor_mutated-2-ingress
      app: distractor_mutated-2-app
    max_attempts: 1
