apiVersion: batch/v1
kind: Job
metadata:
  name: spark-pi-team-a
  namespace: spark-team-a
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: spark-pi-team-a
        component: driver
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-submit
        image: apache/spark:3.5.3
        command:
        - /bin/bash
        - -c
        - |
          echo "Running SparkPi for team-a"
          export SPARK_LOCAL_IP=$(hostname -i)
          /opt/spark/bin/spark-submit \
            --master local[2] \
            --driver-memory 512m \
            --class org.apache.spark.examples.SparkPi \
            /opt/spark/examples/jars/spark-examples_2.12-3.5.3.jar \
            1000
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
      restartPolicy: Never
