apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: repeat-ray-worker-scaling
spec:
  prompt_mode: progressive
  namespaces:
    - ray
  stages:
    - id: ray_worker_scale_first
      service: ray
      case: worker_scaling
      namespaces:
        - ray
    - id: ray_worker_scale_second
      service: ray
      case: worker_scaling
      namespaces:
        - ray
