apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-b94da73f15-distractor_mutated-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - distractor_mutated-1-ingress
  - distractor_mutated-1-app
  - distractor_mutated-2-default
  stages:
  - id: stage_01_nginx-ingress_ingress_class_routing
    service: nginx-ingress
    case: ingress_class_routing
    namespaces:
    - distractor_mutated-1-ingress
    - distractor_mutated-1-app
    namespace_binding:
      ingress: distractor_mutated-1-ingress
      app: distractor_mutated-1-app
    max_attempts: 1
  - id: stage_02_demo_configmap-update
    service: demo
    case: configmap-update
    namespaces:
    - distractor_mutated-2-default
    namespace_binding:
      default: distractor_mutated-2-default
    max_attempts: 1
