apiVersion: v1
kind: Pod
metadata:
  name: oracle-client
  labels:
    app: oracle-client
spec:
  restartPolicy: Always
  containers:
    - name: oracle
      image: nicolaka/netshoot@sha256:47b907d662d139d1e2f22bfe14f4efca1e3f1feed283572f47c970c780c03b61
      command:
        - sleep
        - "3600"
