apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-9008a76a66-history_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - history_mutated-cluster_x
  stages:
  - id: stage_01_rabbitmq-experiments_manual_policy_sync
    service: rabbitmq-experiments
    case: manual_policy_sync
    namespaces:
    - history_mutated-cluster_x
    namespace_binding:
      default: history_mutated-cluster_x
    param_overrides: {}
    max_attempts: 1
  - id: stage_02_rabbitmq-experiments_manual_user_permission
    service: rabbitmq-experiments
    case: manual_user_permission
    namespaces:
    - history_mutated-cluster_x
    namespace_binding:
      default: history_mutated-cluster_x
    param_overrides: {}
    max_attempts: 1
