apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-98d3e99b9d-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-team_a
  - control-1-team_b
  - control-1-team_c
  - control-1-team_d
  stages:
  - id: stage_01_spark_spark_multi_tenant_job_execution
    service: spark
    case: spark_multi_tenant_job_execution
    namespaces:
    - control-1-team_a
    - control-1-team_b
    - control-1-team_c
    - control-1-team_d
    namespace_binding:
      team_a: control-1-team_a
      team_b: control-1-team_b
      team_c: control-1-team_c
      team_d: control-1-team_d
    max_attempts: 1
