apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: repeat-ray-job-execution-param-sweep
spec:
  prompt_mode: progressive
  namespaces:
    - ray
  stages:
    - id: ray_job_execution_first
      service: ray
      case: job_execution
      namespaces:
        - ray
      param_overrides:
        cluster_prefix: ray-ps
        worker_replicas: 1
        expected_output: pong-ps
    - id: ray_job_execution_second
      service: ray
      case: job_execution
      namespaces:
        - ray
      param_overrides:
        cluster_prefix: ray-ps
        worker_replicas: 1
        expected_output: pong-ps
