apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: repeat-demo-configmap-two-ns-value-sweep
spec:
  prompt_mode: progressive
  namespaces:
    - source
    - target
  stages:
    - id: demo_configmap_two_ns_first
      service: demo
      case: configmap-update-two-ns
      namespaces:
        - source
        - target
      param_overrides:
        source_value: left-sweep
        target_value: right-sweep
    - id: demo_configmap_two_ns_second
      service: demo
      case: configmap-update-two-ns
      namespaces:
        - source
        - target
      param_overrides:
        source_value: left-sweep
        target_value: right-sweep
