apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: repeat-ray-worker-scaling-param-sweep
spec:
  prompt_mode: progressive
  namespaces:
    - ray
  stages:
    - id: ray_worker_scale_first
      service: ray
      case: worker_scaling
      namespaces:
        - ray
      param_overrides:
        cluster_prefix: ray-ps
        source_worker_replicas: 1
        target_worker_replicas: 2
    - id: ray_worker_scale_second
      service: ray
      case: worker_scaling
      namespaces:
        - ray
      param_overrides:
        cluster_prefix: ray-ps
        source_worker_replicas: 1
        target_worker_replicas: 2
