apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: repeat-spark-pi-param-sweep
spec:
  prompt_mode: progressive
  namespaces:
    - spark
  stages:
    - id: spark_pi_first
      service: spark
      case: spark_pi_job_execution
      namespaces:
        - spark
      param_overrides:
        service_account_name: spark-ps
        job_name: spark-pi-ps
        iterations: 256
    - id: spark_pi_second
      service: spark
      case: spark_pi_job_execution
      namespaces:
        - spark
      param_overrides:
        service_account_name: spark-ps
        job_name: spark-pi-ps
        iterations: 256
