#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "${SCRIPT_DIR}/../../lib/common.sh"

# Current case: nginx-ingress/rollback-rehearsal
# Strategy: native_shell
# Notes: Review-only rollback planner. It captures the live ingress controller,
# ConfigMap, and application Ingresses, then writes a rollback script into the
# rollback-rehearsal ConfigMap without mutating the running cluster.

static_solver_export_nginx_defaults

app_ns="${BENCH_NS_APP}"
ingress_ns="${BENCH_NS_INGRESS}"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

kubectl -n "${ingress_ns}" get deploy ingress-nginx-controller -o json > "${tmp_dir}/deploy.json" 2>/dev/null || printf '{}\n' > "${tmp_dir}/deploy.json"
kubectl -n "${ingress_ns}" get configmap ingress-nginx-controller -o json > "${tmp_dir}/configmap.json" 2>/dev/null || printf '{}\n' > "${tmp_dir}/configmap.json"
kubectl -n "${app_ns}" get ingress -o json > "${tmp_dir}/ingress.json" 2>/dev/null || printf '{"items":[]}\n' > "${tmp_dir}/ingress.json"

script_path="${STATIC_SOLVER_STAGE_DIR}/rollback.sh"
python3 - "${tmp_dir}" "${app_ns}" "${ingress_ns}" > "${script_path}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

tmp = Path(sys.argv[1])
app_ns = sys.argv[2]
ingress_ns = sys.argv[3]


def load_json(name: str):
    path = tmp / name
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(errors="ignore"))
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def shell_single_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def json_pointer_escape(value: str) -> str:
    return value.replace("~", "~0").replace("/", "~1")


deploy = load_json("deploy.json")
configmap = load_json("configmap.json")
ingress_list = load_json("ingress.json")

containers = (((deploy.get("spec") or {}).get("template") or {}).get("spec") or {}).get("containers") or []
controller = containers[0] if containers and isinstance(containers[0], dict) else {}
args = controller.get("args") or []
if not isinstance(args, list):
    args = []
args = [str(arg) for arg in args]

data = configmap.get("data") or {}
if not isinstance(data, dict):
    data = {}

items = ingress_list.get("items") or []
if not isinstance(items, list):
    items = []

ingresses: list[tuple[str, list[str]]] = []
for item in items:
    if not isinstance(item, dict):
        continue
    metadata = item.get("metadata") or {}
    if not isinstance(metadata, dict):
        continue
    name = str(metadata.get("name") or "")
    annotations = metadata.get("annotations") or {}
    if not isinstance(annotations, dict):
        annotations = {}
    nginx_keys = sorted(
        str(key) for key in annotations
        if str(key).startswith("nginx.ingress.kubernetes.io/")
    )
    ingresses.append((name, nginx_keys))

print("#!/usr/bin/env bash")
print("set -euo pipefail")
print()
print("# Review-only rollback rehearsal script for ingress-nginx.")
print("# Generated by the static solver. Review each command before execution.")
print(f'APP_NS="${{APP_NS:-{app_ns}}}"')
print(f'INGRESS_NS="${{INGRESS_NS:-{ingress_ns}}}"')
print()
print("# 1. Review controller deployment arguments and remove non-default flags")
print("#    from a copied manifest before applying it.")
print('kubectl -n "${INGRESS_NS}" get deploy ingress-nginx-controller -o yaml \\')
print('  > /tmp/ingress-nginx-controller.rollback.yaml')
if args:
    print("# Current controller args captured during rehearsal:")
    for arg in args:
        print(f"#   - {arg}")
else:
    print("# No controller args were captured.")
print("# Edit /tmp/ingress-nginx-controller.rollback.yaml to remove workflow-added")
print("# flags such as class overrides or watch toggles, then apply it:")
print('kubectl -n "${INGRESS_NS}" apply -f /tmp/ingress-nginx-controller.rollback.yaml')
print()

print("# 2. Remove non-default ingress-nginx ConfigMap keys after review.")
if data:
    for key in sorted(data):
        escaped = json_pointer_escape(str(key))
        print(
            'kubectl -n "${INGRESS_NS}" patch configmap ingress-nginx-controller '
            f'--type=json -p={shell_single_quote(json.dumps([{"op": "remove", "path": f"/data/{escaped}"}]))}'
        )
else:
    print("# No ConfigMap data keys were captured.")
print()

print("# 3. Remove nginx-specific annotations from application Ingresses after review.")
if ingresses:
    for name, annotation_keys in ingresses:
        if not name:
            continue
        print(f"# Ingress: {name}")
        if annotation_keys:
            for key in annotation_keys:
                print(f"kubectl -n \"${{APP_NS}}\" annotate ingress {name} {shell_single_quote(key + '-')}")
        else:
            print("# No nginx.ingress.kubernetes.io/* annotations captured.")
        print()
else:
    print("# No Ingress resources were captured.")
    print()

print("# 4. Restart the controller after the reviewed rollback edits are applied.")
print('kubectl -n "${INGRESS_NS}" rollout restart deploy/ingress-nginx-controller')
print('kubectl -n "${INGRESS_NS}" rollout status deploy/ingress-nginx-controller --timeout=180s')
PY

kubectl -n "${app_ns}" create configmap rollback-rehearsal \
  --from-file=rollback.sh="${script_path}" \
  --dry-run=client -o yaml | kubectl -n "${app_ns}" apply -f -

static_solver_write_submit "prepared ingress-nginx rollback rehearsal script without executing it"
