apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: rabbitmq-blue-green-migration-single
spec:
  prompt_mode: concat_blind
  namespaces:
    - cluster_source
    - cluster_target
  stages:
    - id: stage_1_migrate_source_to_target
      service: rabbitmq-experiments
      case: blue_green_migration
      namespaces:
        - cluster_source
        - cluster_target
      namespace_binding:
        default: cluster_target
        source: cluster_source
        target: cluster_target
      max_attempts: 3
      param_overrides:
        blue_cluster_prefix: rabbitmq
        green_cluster_prefix: rabbitmq
