apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: workflow-demo
spec:
  prompt_mode: concat_blind
  namespaces:
  - cluster_a
  - cluster_b
  stages:
  - id: stage_1
    service: demo
    case: configmap-update
    namespaces:
    - cluster_a
    param_overrides:
      target_value: "1"
  - id: stage_2
    service: demo
    case: configmap-update
    namespaces:
    - cluster_a
    param_overrides:
      target_value: "2"
  - id: stage_3
    service: demo
    case: configmap-update
    namespaces:
    - cluster_a
    param_overrides:
      target_value: "3"
  - id: stage_4
    service: demo
    case: configmap-update
    namespaces:
    - cluster_a
    param_overrides:
      target_value: "4"
  - id: stage_5
    service: demo
    case: configmap-update
    namespaces:
    - cluster_b
    param_overrides:
      target_value: "1"
  - id: stage_6
    service: demo
    case: configmap-update
    namespaces:
    - cluster_a
    param_overrides:
      target_value: "6"
