apiVersion: v1
kind: Pod
metadata:
  name: file-realm-gen
spec:
  containers:
    - name: file-realm-gen
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
      command: ["sleep", "infinity"]
  restartPolicy: Never
