apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-pi-role
  namespace: spark-pi
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - persistentvolumeclaims
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  - patch
