apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-fc615030b4-order_b-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - order_b-1-default
  - order_b-2-default
  - order_b-3-ingress
  - order_b-3-app
  stages:
  - id: stage_01_mongodb_user-management
    service: mongodb
    case: user-management
    namespaces:
    - order_b-1-default
    namespace_binding:
      default: order_b-1-default
    max_attempts: 1
  - id: stage_02_mongodb_health-check-recovery
    service: mongodb
    case: health-check-recovery
    namespaces:
    - order_b-2-default
    namespace_binding:
      default: order_b-2-default
    max_attempts: 1
  - id: stage_03_nginx-ingress_ingress_route_ready
    service: nginx-ingress
    case: ingress_route_ready
    namespaces:
    - order_b-3-ingress
    - order_b-3-app
    namespace_binding:
      ingress: order_b-3-ingress
      app: order_b-3-app
    max_attempts: 1
