apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cockroachdb
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: crdb-cluster
      app.kubernetes.io/name: cockroachdb
  endpoints:
    - port: http
      path: /_status/vars
      interval: 30s
