apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-3d7457b1ec-history_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - history_mutated-cluster_a
  - history_mutated-cluster_b
  - history_mutated-cluster_x
  stages:
  - id: stage_01_rabbitmq-experiments_blue_green_migration
    service: rabbitmq-experiments
    case: blue_green_migration
    namespaces:
    - history_mutated-cluster_a
    - history_mutated-cluster_b
    namespace_binding:
      default: history_mutated-cluster_b
      source: history_mutated-cluster_a
      target: history_mutated-cluster_b
    param_overrides:
      blue_cluster_prefix: rabbitmq
      green_cluster_prefix: rabbitmq
    max_attempts: 1
  - id: stage_02_rabbitmq-experiments_manual_monitoring
    service: rabbitmq-experiments
    case: manual_monitoring
    namespaces:
    - history_mutated-cluster_x
    namespace_binding:
      default: history_mutated-cluster_x
    param_overrides: {}
    max_attempts: 1
