apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
  namespace: ray
  labels:
    app: ray-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      containers:
      - name: ray-head
        image: rayproject/ray:2.8.0
        command:
          - sh
          - -c
          - |
            ray start --head --port=6379 --dashboard-host=0.0.0.0 --dashboard-port=8265 --block
        ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
