apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-fe04d0b3b7-history_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - history_mutated-cluster_a
  stages:
  - id: stage_01_rabbitmq-experiments_manual_skip_upgrade
    service: rabbitmq-experiments
    case: manual_skip_upgrade
    namespaces:
    - history_mutated-cluster_a
    namespace_binding:
      default: history_mutated-cluster_a
    param_overrides:
      cluster_prefix: rabbitmq-cluster-a
      from_version: '3.9'
      to_version: '3.10'
    max_attempts: 1
  - id: stage_02_rabbitmq-experiments_manual_tls_rotation
    service: rabbitmq-experiments
    case: manual_tls_rotation
    namespaces:
    - history_mutated-cluster_a
    namespace_binding:
      default: history_mutated-cluster_a
    param_overrides:
      cluster_prefix: rabbitmq-cluster-a
    max_attempts: 1
