apiVersion: v1
kind: Service
metadata:
  name: es-http
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: https
      port: 9200
      targetPort: 9200
