apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-21b5622288-order_a-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - order_a-1-default
  - order_a-2-default
  - order_a-3-default
  stages:
  - id: stage_01_mongodb_arbiters
    service: mongodb
    case: arbiters
    namespaces:
    - order_a-1-default
    namespace_binding:
      default: order_a-1-default
    max_attempts: 1
  - id: stage_02_mongodb_health-check-recovery
    service: mongodb
    case: health-check-recovery
    namespaces:
    - order_a-2-default
    namespace_binding:
      default: order_a-2-default
    max_attempts: 1
  - id: stage_03_ray_cluster_teardown
    service: ray
    case: cluster_teardown
    namespaces:
    - order_a-3-default
    namespace_binding:
      default: order_a-3-default
    max_attempts: 1
