apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config-new
  namespace: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: es-cluster
    node.name: ${POD_NAME}
    node.roles: [ data, ingest ]
    node.attr.tier: warm
    network.host: 0.0.0.0
    discovery.seed_hosts:
      - es-cluster-0.es-cluster
      - es-cluster-1.es-cluster
      - es-cluster-2.es-cluster
      - es-data-new-0.es-data-new
      - es-data-new-1.es-data-new
    node.store.allow_mmap: false
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: es-data-new
  namespace: elasticsearch
spec:
  clusterIP: None
  selector:
    app: es-data-new
  ports:
    - name: transport
      port: 9300
      targetPort: 9300
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data-new
  namespace: elasticsearch
spec:
  serviceName: es-data-new
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: es-data-new
  template:
    metadata:
      labels:
        app: es-data-new
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          volumeMounts:
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: es-config
          configMap:
            name: es-config-new
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
