apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: order_delta-ef6c1117f2-order_b-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - order_b-cluster_x
  - order_b-cluster_a
  - order_b-cluster_b
  stages:
  - id: stage_01_rabbitmq-experiments_manual_user_permission
    service: rabbitmq-experiments
    case: manual_user_permission
    namespaces:
    - order_b-cluster_x
    namespace_binding:
      default: order_b-cluster_x
    param_overrides: {}
    max_attempts: 1
  - id: stage_02_rabbitmq-experiments_blue_green_migration
    service: rabbitmq-experiments
    case: blue_green_migration
    namespaces:
    - order_b-cluster_a
    - order_b-cluster_b
    namespace_binding:
      default: order_b-cluster_b
      source: order_b-cluster_a
      target: order_b-cluster_b
    param_overrides:
      blue_cluster_prefix: rabbitmq
      green_cluster_prefix: rabbitmq
    max_attempts: 1
  - id: stage_03_rabbitmq-experiments_manual_monitoring
    service: rabbitmq-experiments
    case: manual_monitoring
    namespaces:
    - order_b-cluster_x
    namespace_binding:
      default: order_b-cluster_x
    param_overrides: {}
    max_attempts: 1
