apiVersion: v1
kind: ConfigMap
metadata:
  name: es-alpha-config
data:
  elasticsearch.yml: |
    cluster.name: es-alpha
    node.name: ${POD_NAME}
    node.roles: [ master, data, ingest ]
    network.host: 0.0.0.0
    discovery.seed_hosts:
      - es-alpha-0.es-alpha
      - es-alpha-1.es-alpha
      - es-alpha-2.es-alpha
    cluster.initial_master_nodes:
      - es-alpha-0
      - es-alpha-1
      - es-alpha-2
    node.store.allow_mmap: false
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
