apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-83ba5ee648-history_mutated-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - history_mutated-1-ingress
  - history_mutated-1-app
  - history_mutated-2-default
  stages:
  - id: stage_01_nginx-ingress_header_canary_routing
    service: nginx-ingress
    case: header_canary_routing
    namespaces:
    - history_mutated-1-ingress
    - history_mutated-1-app
    namespace_binding:
      ingress: history_mutated-1-ingress
      app: history_mutated-1-app
    max_attempts: 1
  - id: stage_02_elasticsearch_master-downscale-voting-exclusions
    service: elasticsearch
    case: master-downscale-voting-exclusions
    namespaces:
    - history_mutated-2-default
    namespace_binding:
      default: history_mutated-2-default
    max_attempts: 1
