apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-3efc127a97-history_mutated-concat_stateful
spec:
  prompt_mode: concat_stateful
  namespaces:
  - history_mutated-1-default
  - history_mutated-2-default
  stages:
  - id: stage_01_ray_version_upgrade
    service: ray
    case: version_upgrade
    namespaces:
    - history_mutated-1-default
    namespace_binding:
      default: history_mutated-1-default
    max_attempts: 1
  - id: stage_02_elasticsearch_snapshot-repo-setup
    service: elasticsearch
    case: snapshot-repo-setup
    namespaces:
    - history_mutated-2-default
    namespace_binding:
      default: history_mutated-2-default
    max_attempts: 1
