apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-3efc127a97-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_elasticsearch_snapshot-repo-setup
    service: elasticsearch
    case: snapshot-repo-setup
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
