apiVersion: apps/v1
kind: Deployment
metadata:
  name: __CLUSTER_PREFIX__-master
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __CLUSTER_PREFIX__-master
  template:
    metadata:
      labels:
        app: __CLUSTER_PREFIX__-master
        component: master
    spec:
      serviceAccountName: __SERVICE_ACCOUNT__
      containers:
      - name: spark-master
        image: __SPARK_IMAGE__
        command:
        - /bin/bash
        - -c
        - |
          unset SPARK_MASTER_PORT
          /opt/spark/sbin/start-master.sh
          tail -f /opt/spark/logs/*
        ports:
        - containerPort: 7077
          name: spark
        - containerPort: 8080
          name: webui
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
