apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.6.0
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: es-http-ca
          mountPath: /etc/es-http-ca
          readOnly: true
  volumes:
    - name: es-http-ca
      configMap:
        name: es-http-ca
        items:
          - key: ca.crt
            path: ca.crt
