#!/usr/bin/env bash
# Rollback script: revert ingress-nginx non-default configuration to vanilla defaults.
# Generated by inspection of cluster state on 2026-06-14.
#
# Non-default changes detected (to be reverted):
#   1. Deployment patch: --watch-ingress-without-class=false was appended to controller
#      args AFTER the initial apply.  The original last-applied-configuration had
#      --watch-ingress-without-class=true; the live spec now carries both flags, with
#      =false taking precedence at runtime.  Rollback replaces the full args list with
#      the exact original set (removing =false).
#   2. IngressClass ingress-1 (controller: k8s.io/ingress-nginx-1) -- non-standard,
#      not part of the stock ingress-nginx 1.14.1 install.
#   3. IngressClass ingress-2 (controller: k8s.io/ingress-nginx-2) -- non-standard,
#      not part of the stock ingress-nginx 1.14.1 install.
#
# Already at vanilla defaults (no action needed):
#   - ingress-nginx-controller ConfigMap: data is null (empty) -- unchanged from initial apply.
#   - No Ingress resources exist in any namespace.
#
# DO NOT run this script while the cluster is serving traffic unless a planned outage
# or maintenance window is in effect.  The deployment patch will trigger a rolling
# restart of the ingress-nginx-controller pod.

set -euo pipefail

echo "=== ingress-nginx rollback: reverting non-default configuration ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Restore controller deployment args to the original last-applied-configuration.
#    Replace the entire args list so that the spurious --watch-ingress-without-class=false
#    entry (added by a later patch) is removed.
#    Note: $(POD_NAMESPACE) is a Kubernetes env-var substitution token, not a shell
#    variable -- it must be passed as a literal string in the JSON patch.
# ---------------------------------------------------------------------------
echo "[1/3] Patching ingress-nginx-controller deployment to restore original args ..."
kubectl -n ingress-nginx patch deployment ingress-nginx-controller \
  --type=json \
  -p='[
    {
      "op": "replace",
      "path": "/spec/template/spec/containers/0/args",
      "value": [
        "/nginx-ingress-controller",
        "--election-id=ingress-nginx-leader",
        "--controller-class=k8s.io/ingress-nginx",
        "--ingress-class=nginx",
        "--configmap=$(POD_NAMESPACE)/ingress-nginx-controller",
        "--validating-webhook=:8443",
        "--validating-webhook-certificate=/usr/local/certificates/cert",
        "--validating-webhook-key=/usr/local/certificates/key",
        "--watch-ingress-without-class=true",
        "--publish-status-address=localhost"
      ]
    }
  ]'

echo "    Waiting for rollout ..."
kubectl -n ingress-nginx rollout status deployment/ingress-nginx-controller --timeout=120s
echo "    Deployment rollout complete."
echo ""

# ---------------------------------------------------------------------------
# 2. Reset the ingress-nginx-controller ConfigMap to empty data.
#    The ConfigMap currently has no custom data (data: null), so this is a
#    no-op in the current state but is included for idempotency in case data
#    keys were added between inspection and execution.
# ---------------------------------------------------------------------------
echo "[2/3] Resetting ingress-nginx-controller ConfigMap to empty data (vanilla) ..."
kubectl -n ingress-nginx patch configmap ingress-nginx-controller \
  --type=merge \
  -p='{"data": null}'
echo "    ConfigMap reset."
echo ""

# ---------------------------------------------------------------------------
# 3. Remove the two non-standard IngressClass resources.
#    The standard ingress-nginx install ships only the 'nginx' IngressClass.
#    ingress-1 and ingress-2 are additional classes that are not part of the
#    default manifests.
# ---------------------------------------------------------------------------
echo "[3/3] Deleting non-standard IngressClass resources (ingress-1, ingress-2) ..."
kubectl delete ingressclass ingress-1 ingress-2 --ignore-not-found
echo "    IngressClass cleanup done."
echo ""

echo "=== Rollback complete. ==="
echo ""
echo "Verify with:"
echo "  kubectl -n ingress-nginx get deployment ingress-nginx-controller -o jsonpath='{.spec.template.spec.containers[0].args}'"
echo "  kubectl get ingressclass"
echo "  kubectl -n ingress-nginx get configmap ingress-nginx-controller -o yaml"
