apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
data:
  metricbeat.yml: |
    metricbeat.modules:
      - module: elasticsearch
        xpack.enabled: true
        period: 10s
        hosts: ["https://localhost:9200"]
        username: elastic
        password: ${ELASTIC_PASSWORD}
        ssl.certificate_authorities: ["/etc/es-http/ca.crt"]

    output.elasticsearch:
      hosts: ["http://monitoring-es-htp:9200"]

    logging.to_files: false
    logging.to_syslog: false
