apiVersion: v1
kind: Secret
metadata:
  name: ${BENCH_PARAM_CLUSTER_PREFIX}-tls
type: Opaque
data:
  ca.crt: <base64-encoded-ca>
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: ${BENCH_PARAM_CLUSTER_PREFIX}-erlang-cookie
type: Opaque
data:
  cookie: <base64-encoded-cookie>
