#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "${SCRIPT_DIR}/../../lib/common.sh"

# Current case: ray/rollback-rehearsal
# Strategy: native_shell
# Notes: Review-only rollback planner. It snapshots the live Ray state and writes
# a rollback script to ConfigMap/rollback-rehearsal without executing it.

static_solver_export_namespace_if_unset "ray"

ns="${BENCH_NAMESPACE}"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

capture_cmd() {
  local name="${1:?output name is required}"
  shift
  "$@" > "${tmp_dir}/${name}" 2>&1 || true
}

capture_cmd pods.txt kubectl -n "${ns}" get pods -o wide
capture_cmd deployments.json kubectl -n "${ns}" get deploy ray-head ray-worker -o json
capture_cmd service.json kubectl -n "${ns}" get svc ray-head -o json
capture_cmd service.yaml kubectl -n "${ns}" get svc ray-head -o yaml

script_path="${STATIC_SOLVER_STAGE_DIR}/rollback.sh"
python3 - "${tmp_dir}" > "${script_path}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

tmp = Path(sys.argv[1])
default_image = "rayproject/ray:2.9.0"
default_workers = 1
default_service_ports = {6379}


def load_json(name: str) -> dict:
    path = tmp / name
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(errors="ignore"))
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def deployment_item(payload: dict, name: str) -> dict:
    for item in payload.get("items", []) or []:
        metadata = item.get("metadata") or {}
        if metadata.get("name") == name:
            return item if isinstance(item, dict) else {}
    return {}


def container_image(item: dict) -> str:
    containers = (((item.get("spec") or {}).get("template") or {}).get("spec") or {}).get("containers") or []
    if not containers or not isinstance(containers[0], dict):
        return ""
    return str(containers[0].get("image") or "")


def service_ports(payload: dict) -> list[tuple[str, int]]:
    ports: list[tuple[str, int]] = []
    for item in ((payload.get("spec") or {}).get("ports") or []):
        if not isinstance(item, dict):
            continue
        try:
            port = int(item.get("port"))
        except (TypeError, ValueError):
            continue
        ports.append((str(item.get("name") or f"port-{port}"), port))
    return ports


deployments = load_json("deployments.json")
service = load_json("service.json")
head = deployment_item(deployments, "ray-head")
worker = deployment_item(deployments, "ray-worker")
worker_replicas = int((worker.get("spec") or {}).get("replicas", 0) or 0)
head_image = container_image(head) or default_image
worker_image = container_image(worker) or default_image
ports = service_ports(service)
port_lines = [f"#   - {name}: {port}" for name, port in ports] or ["#   - no service ports captured"]

print("#!/usr/bin/env bash")
print("set -euo pipefail")
print()
print("# Review-only Ray rollback rehearsal script.")
print("# Generated by the static solver. Review every command before execution.")
print('NS="${NS:-ray}"')
print(f'BASELINE_WORKERS="${{BASELINE_WORKERS:-{default_workers}}}"')
print(f'BASELINE_IMAGE="${{BASELINE_IMAGE:-{default_image}}}"')
print()
print("# Current cluster snapshot captured during rehearsal:")
print(f"#   head image: {head_image}")
print(f"#   worker image: {worker_image}")
print(f"#   worker replicas: {worker_replicas}")
print("#   service ports:")
for line in port_lines:
    print(line)
print()
print("# 1. Capture the live state again immediately before running any rollback.")
print('kubectl -n "${NS}" get pods -o wide')
print('kubectl -n "${NS}" get deploy ray-head ray-worker -o yaml')
print('kubectl -n "${NS}" get svc ray-head -o yaml')
print()
print("# 2. Revert worker count and Ray images to the reviewed baseline.")
print('kubectl -n "${NS}" scale deploy/ray-worker --replicas="${BASELINE_WORKERS}"')
print('kubectl -n "${NS}" set image deploy/ray-head ray-head="${BASELINE_IMAGE}"')
print('kubectl -n "${NS}" set image deploy/ray-worker ray-worker="${BASELINE_IMAGE}"')
print('kubectl -n "${NS}" rollout status deploy/ray-head --timeout=300s')
print('kubectl -n "${NS}" rollout status deploy/ray-worker --timeout=300s')
print()
print("# 3. If non-default service ports were added, remove them in a reviewed copy")
print("#    of the Service manifest before applying it.")
print('kubectl -n "${NS}" get svc ray-head -o yaml > /tmp/ray-head.rollback.yaml')
extra_ports = [port for _, port in ports if port not in default_service_ports]
if extra_ports:
    print("# Current non-default ports to remove from /tmp/ray-head.rollback.yaml:")
    for port in extra_ports:
        print(f"#   - {port}")
else:
    print("# No non-default service ports were captured.")
print("# Keep only the default GCS port 6379 in that reviewed manifest, then apply:")
print('kubectl -n "${NS}" apply -f /tmp/ray-head.rollback.yaml')
print()
print("# 4. Re-check final state after the reviewed rollback.")
print('kubectl -n "${NS}" get deploy ray-head ray-worker -o wide')
print('kubectl -n "${NS}" get svc ray-head -o yaml')
print('kubectl -n "${NS}" get pods -o wide')
print()
print("# Captured pod snapshot from the rehearsal point:")
for raw_line in (tmp / "pods.txt").read_text(errors="ignore").splitlines():
    print(f"# {raw_line}")
print()
print("# Captured Service snapshot from the rehearsal point:")
print("cat <<'EOF_SERVICE'")
print((tmp / "service.yaml").read_text(errors="ignore").rstrip())
print("EOF_SERVICE")
PY

kubectl -n "${ns}" create configmap rollback-rehearsal \
  --from-file=rollback.sh="${script_path}" \
  --dry-run=client -o yaml | kubectl -n "${ns}" apply -f -

static_solver_write_submit "prepared rollback-rehearsal ConfigMap"
