apiVersion: v1
kind: Secret
metadata:
  name: elastic-password
  namespace: elasticsearch
type: Opaque
stringData:
  password: elasticpass-old
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-password-next
  namespace: elasticsearch
type: Opaque
stringData:
  password: elasticpass-new
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-password-prev
  namespace: elasticsearch
data:
  password: elasticpass-old
