apiVersion: v1
kind: Service
metadata:
  name: es-transport
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es-http
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: https
      port: 9200
      targetPort: 9200
