apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-ad758ab5ab-distractor_mutated-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - distractor_mutated-1-default
  - distractor_mutated-2-default
  stages:
  - id: stage_01_ray_version_upgrade
    service: ray
    case: version_upgrade
    namespaces:
    - distractor_mutated-1-default
    namespace_binding:
      default: distractor_mutated-1-default
    max_attempts: 1
  - id: stage_02_rabbitmq-experiments_classic_queue
    service: rabbitmq-experiments
    case: classic_queue
    namespaces:
    - distractor_mutated-2-default
    namespace_binding:
      default: distractor_mutated-2-default
    max_attempts: 1
