apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: distractor_delta-a14e304dd8-distractor_mutated-concat_blind
spec:
  prompt_mode: concat_blind
  namespaces:
  - distractor_mutated-cluster_a
  stages:
  - id: stage_01_mongodb_setup-rbac-drift-app
    service: mongodb
    case: setup-rbac-drift-app
    namespaces:
    - distractor_mutated-cluster_a
    namespace_binding:
      default: distractor_mutated-cluster_a
    param_overrides: {}
    max_attempts: 1
  - id: stage_02_mongodb_setup-rbac-drift-reporting
    service: mongodb
    case: setup-rbac-drift-reporting
    namespaces:
    - distractor_mutated-cluster_a
    namespace_binding:
      default: distractor_mutated-cluster_a
    param_overrides: {}
    max_attempts: 1
