apiVersion: benchmark/v1alpha1
kind: Workflow
metadata:
  name: history_delta-8cb64135ba-control-progressive
spec:
  prompt_mode: progressive
  namespaces:
  - control-1-default
  stages:
  - id: stage_01_ray_version_upgrade
    service: ray
    case: version_upgrade
    namespaces:
    - control-1-default
    namespace_binding:
      default: control-1-default
    max_attempts: 1
