#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "${SCRIPT_DIR}/../../lib/common.sh"

# Current case: spark/rollback-rehearsal
# Strategy: native_shell
# Notes: Review-only rollback planner. It snapshots the live SparkPi namespace
# and writes a rollback script to ConfigMap/rollback-rehearsal without executing it.

static_solver_export_namespace_if_unset "spark-pi"

ns="${BENCH_NAMESPACE}"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

capture_cmd() {
  local name="${1:?output name is required}"
  shift
  "$@" > "${tmp_dir}/${name}" 2>&1 || true
}

capture_cmd deploys.yaml kubectl -n "${ns}" get deployments -o yaml
capture_cmd jobs.yaml kubectl -n "${ns}" get jobs -o yaml
capture_cmd rbac.yaml kubectl -n "${ns}" get role,rolebinding,serviceaccount -o yaml
capture_cmd configmaps.txt kubectl -n "${ns}" get configmaps

script_path="${STATIC_SOLVER_STAGE_DIR}/rollback.sh"
cat > "${script_path}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# Review-only Spark rollback rehearsal script.
# Generated by the static solver. Review each command before execution.
NS="${NS:-spark-pi}"
BASELINE_IMAGE="${BASELINE_IMAGE:-apache/spark:3.5.3}"

# 1. Capture the current state again immediately before any rollback.
kubectl -n "${NS}" get deployments -o yaml
kubectl -n "${NS}" get jobs -o yaml
kubectl -n "${NS}" get role,rolebinding,serviceaccount -o yaml

# 2. Review the copied manifests, revert any non-default image, resource, RBAC,
#    or job settings, and then re-apply only the approved rollback manifests.
kubectl -n "${NS}" get deployments -o yaml > /tmp/spark-pi.deployments.rollback.yaml
kubectl -n "${NS}" get jobs -o yaml > /tmp/spark-pi.jobs.rollback.yaml
kubectl -n "${NS}" get role,rolebinding,serviceaccount -o yaml > /tmp/spark-pi.rbac.rollback.yaml

# 3. Normalize images back to the reviewed baseline where required.
kubectl -n "${NS}" set image deploy/spark-master spark-master="${BASELINE_IMAGE}"
kubectl -n "${NS}" set image deploy/spark-worker spark-worker="${BASELINE_IMAGE}"
kubectl -n "${NS}" rollout status deploy/spark-master --timeout=300s
kubectl -n "${NS}" rollout status deploy/spark-worker --timeout=300s

# 4. Apply the reviewed rollback manifests.
kubectl -n "${NS}" apply -f /tmp/spark-pi.deployments.rollback.yaml
kubectl -n "${NS}" apply -f /tmp/spark-pi.jobs.rollback.yaml
kubectl -n "${NS}" apply -f /tmp/spark-pi.rbac.rollback.yaml
EOF

{
  printf '\n# Captured deployment snapshot from the rehearsal point:\n'
  cat "${tmp_dir}/deploys.yaml"
  printf '\n# Captured job snapshot from the rehearsal point:\n'
  cat "${tmp_dir}/jobs.yaml"
  printf '\n# Captured RBAC snapshot from the rehearsal point:\n'
  cat "${tmp_dir}/rbac.yaml"
  printf '\n# Captured ConfigMap inventory from the rehearsal point:\n'
  cat "${tmp_dir}/configmaps.txt"
} >> "${script_path}"

kubectl -n "${ns}" create configmap rollback-rehearsal \
  --from-file=rollback.sh="${script_path}" \
  --dry-run=client -o yaml | kubectl -n "${ns}" apply -f -

static_solver_write_submit "prepared rollback-rehearsal ConfigMap"
